algorithm: 'star' # star, scalefree , prox_preferential , cosine , DPP (Dynamic ProxPref)
plot_colormap: nipy_spectral   # turbo, jet, viridis nipy_spectral brg, gist_earth
save_results: True
save_figures: True
metric_path: "results/{algorithm}/metrics"
figure_path: "results/{algorithm}/figures"


num_rounds: 2
num_classes: 10
input_len: 1 # CIFAR: 3  MNIST: 1
num_clients: 99
aggregation_rounds: 3 # defaults to 1 if algorithm is 'star'

#####################
# DATA PREPARE AND IID-ness
config_data:
  dataset: 'MNIST' # **Change input_len** 'MNIST', 'CIFAR10'
  alpha: 0.1 # control how much iid needed in the dataset, lower the more non-iid.
  batch_size: 20
  num_partitions: null #Gets the same value as num_clients (do not change)
  iid: 0 # bool 1:iid  0:non-iid

###################
# DEVICE PARAMETERS
config_fit: # a config that each client will receive
  lr: 0.01 # learning rate to use by the clients
  momentum: 0.9 # momentum used by SGD optimiser on the client side
  epochs: 2 # number of training epochs each clients does in a fit() round


defaults:
  - neighbor_lists: random_weighted_05_50_5.yaml #Change file_name here

