algorithm: prox_preferential
plot_colormap: nipy_spectral   # turbo, jet, viridis nipy_spectral brg, gist_earth
save_results: True
metric_path: "results/proxpref/metrics"
figure_path: "results/proxpref/figures"


num_rounds: 4
num_clients: 100
batch_size: 20
num_classes: 10
aggregation_rounds: 1


alpha: 0.1 # control how much iid needed in the dataset, lower the more non-iid. #NOTE: edeg case occurs when alpha is too small
iid: 1 #bool value for data distribuitions

config_fit: # a config that each client will receive
  lr: 0.01 # learning rate to use by the clients
  momentum: 0.9 # momentum used by SGD optimiser on the client side
  epochs: 2 # number of training epochs each clients does in a fit() round


defaults:
  - model: net
  - neighbor_lists: random_weighted_05_50_5.yaml #Change file_name here

